### ISSUE TITLE
Permission Denied in workingDir

### ISSUE THREAD

**Issue by bbrauzzi** [Duke-GCB/calrissian#105]
I am trying to execute a cwl workflow which runs a application with a non-root user. The problem is that the user has no write permission in the HOME directory which has root's permissions and ownership.

```
Created k8s pod name node-1-pod-bfbhhyxv with id 5d0c2b66-99f7-40f7-b34d-ed38e36042ed
PodMonitor adding node-1-pod-bfbhhyxv
k8s pod 'node-1-pod-bfbhhyxv' started
[node-1-pod-bfbhhyxv] follow_logs start
[node-1-pod-bfbhhyxv] Traceback (most recent call last):
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1210, in get_cache_path
[node-1-pod-bfbhhyxv]     _bypass_ensure_directory(target_path)
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in _bypass_ensure_directory
[node-1-pod-bfbhhyxv]     _bypass_ensure_directory(dirname)
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in _bypass_ensure_directory
[node-1-pod-bfbhhyxv]     _bypass_ensure_directory(dirname)
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in _bypass_ensure_directory
[node-1-pod-bfbhhyxv]     _bypass_ensure_directory(dirname)
[node-1-pod-bfbhhyxv]   [Previous line repeated 1 more time]
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3193, in _bypass_ensure_directory
[node-1-pod-bfbhhyxv]     mkdir(dirname, 0o755)
[node-1-pod-bfbhhyxv] PermissionError: [Errno 13] Permission denied: '/xmPvKt/.cache'
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] During handling of the above exception, another exception occurred:
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] Traceback (most recent call last):
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/bin/s3-slstr-tiling", line 33, in <module>
[node-1-pod-bfbhhyxv]     sys.exit(load_entry_point('a==0.0.1.0', 'console_scripts', 's3-slstr-tiling')())
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/a-0.0.1.0-py3.7.egg/package/ades/cli.py", line 61, in main
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1145, in resource_filename
[node-1-pod-bfbhhyxv]     self, resource_name
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1754, in get_resource_filename
[node-1-pod-bfbhhyxv]     return self._extract_resource(manager, zip_path)
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1783, in _extract_resource
[node-1-pod-bfbhhyxv]     self.egg_name, self._parts(zip_path)
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1212, in get_cache_path
[node-1-pod-bfbhhyxv]     self.extraction_error()
[node-1-pod-bfbhhyxv]   File "/opt/anaconda/envs/env_s3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1192, in extraction_error
[node-1-pod-bfbhhyxv]     raise err
[node-1-pod-bfbhhyxv] pkg_resources.ExtractionError: Can't extract file(s) to egg cache
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] The following error occurred while trying to extract file(s)
[node-1-pod-bfbhhyxv] to the Python egg cache:
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv]   [Errno 13] Permission denied: '/xmPvKt/.cache'
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] The Python egg cache directory is currently set to:
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv]   /xmPvKt/.cache/Python-Eggs
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] Perhaps your account does not have write access to this directory?
[node-1-pod-bfbhhyxv] You can change the cache directory by setting the PYTHON_EGG_CACHE
[node-1-pod-bfbhhyxv] environment variable to point to an accessible directory.
[node-1-pod-bfbhhyxv] 
[node-1-pod-bfbhhyxv] follow_logs end
```
following is the pod's manifest that calrissian generates to run the first node of the cwl.

```
apiVersion: v1

kind: Pod
metadata:
  labels: {}
  name: node-1-pod-bfbhhyxv
spec:
  containers:
  - args:
    - s3-slstr-tiling --input_reference /var/lib/cwl/stg1fb5cdce-b364-45f5-b9e2-689897239d27/input-data
      --tiling_level 5
    command:
    - /bin/sh
    - -c
    env:
    - name: HOME
      value: /xmPvKt
    - name: PATH
      value: /opt/anaconda/envs/env_s3/bin/:/opt/anaconda/envs/notebook/bin:/opt/anaconda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - name: PREFIX
      value: /opt/anaconda/envs/env_s3
    - name: TMPDIR
      value: /tmp
    image: terradue/s3-slstr-preproc:1.0
    name: node-1-container
    resources:
      requests:
        cpu: '1'
        memory: 1024Mi
    volumeMounts:
    - mountPath: /xmPvKt
      name: t2demo-volume-tmpout
      readOnly: false
      subPath: u_olnaqc
    - mountPath: /tmp
      name: tmpdir
    - mountPath: /var/lib/cwl/stg1fb5cdce-b364-45f5-b9e2-689897239d27/input-data
      name: t2demo-volume-input-data
      readOnly: true
      subPath: ''
    workingDir: /xmPvKt
  initContainers: []
  restartPolicy: Never
  volumes:
  - name: t2demo-volume-input-data
    persistentVolumeClaim:
      claimName: t2demo-volume-input-data
      readOnly: false
  - name: t2demo-volume-tmpout
    persistentVolumeClaim:
      claimName: t2demo-volume-tmpout
      readOnly: false
  - name: t2demo-volume-output-data
    persistentVolumeClaim:
      claimName: t2demo-volume-output-data
      readOnly: false
  - emptyDir: {}
    name: tmpdir
```

Is there a way to give full permissions to the home directory to any user when running calrissian's job (eg. CalrissianJob-revsort.yaml) ?

thank you very much for your attention

**Comment by bbrauzzi** [comment]
I found the solution.
I added the following securityContext to the Calrissian's job manifest:
```
      securityContext:
        runAsUser: 1000
        runAsGroup: 3000
        fsGroup: 2000
```
for further information please refer to https://kubernetes.io/docs/tasks/configure-pod-container/security-context/

Interesting software, keep up the good work!
