### ISSUE TITLE
Creating an option for job and master pod self-deletion

### ISSUE THREAD

**Issue by CommanderBlop** [Duke-GCB/calrissian#146]
Creating an optional flag for Calrissian container that enables deleting everything - the calrissian job pod, the calrissian job itself via batchV1API through granting the service account additional permission.

**Comment by fabricebrito** [comment]
calrissian is an executable that does really know if it's running in a k8s job or pod. 

If you want to terminate a k8s job that runs calrissian after the job completion, you could follow this approach: https://kubernetes.io/docs/concepts/workloads/controllers/job/#ttl-mechanism-for-finished-jobs

example:

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: calrissian-revsort-array
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: calrissian
        image: dukegcb/calrissian:latest
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
        command: ["calrissian"]
        args:
        ....
```

@CommanderBlop let me know if that works for you
