### ISSUE TITLE
Add support for pod env from secret

### ISSUE THREAD

**Issue by fabricebrito** [Duke-GCB/calrissian#195]
Allow passing one or more secret ids via the calrissina CLI to set the calrissian spawned pods environment.

E.g.:

`calrissian --env-from-secret secret1 --env-from-secret secret2 --max-ram ...`

Leading to spawned pods with:

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: step1
spec:
  containers:
  - name: step1-container
    ...
    envFrom:
    - secretRef:
        name: secret1
    - secretRef:
        name: secret2
```
