### ISSUE TITLE
Report resource usage by step and overall

### ISSUE THREAD

**Issue by dleehr** [Duke-GCB/calrissian#49]
Our job runner should be able to report how long each step ran for and what resources it used. This will be critical for accounting but could also be used for real-time progress reporting.

@johnbradley and i discussed recently how to accomplish this, and I suggested it would be best addressed by calrissian

Some thoughts:

- My initial idea was to address progress reporting and resource usage in the same mechanism - by watching for jobs issued that match a label or annotation.
- [lando watcher](https://github.com/Duke-GCB/lando/blob/master/lando/k8s/watcher.py) watches k8s events and translates them into rabbitmq messages. This would be useful for reporting real-time updates back to bespin-api through the existing queue.
- Using lando watcher for that purpose is a stretch because lando and bespin aren't concerned with the steps of a CWL workflow or number of scattered tasks.
- Calrissian (as the CWL engine) obviously is concerned with these progress details, so it makes sense to digest and broadcast this information from calrissian
- Calrissian can easily track and report these times in a single JSON file at the end of the execution. This is a good feature for all users, not just bespin/lando integration
- Reporting real-time progress is trickier, as this would likely need to move through the message queue.

**Comment by dleehr** [comment]
Example report:

```
--- 
workflow_summary: 
  cpu_hours: 2.0
  end_time: "11:00:00"
  max_cpu: 2.0
  max_ram: 2048
  memory_hours: 2.0
  start_time: "10:00:00"
  steps: 
    - 
      contents: 
        - 
          cpu: 1
          cpu_hours: 0.25
          end_time: "10:15:00"
          id: qc_2
          memory_hours: 0.125
          ram: 512
          start_time: "10:00:00"
          total_runtime_seconds: 3600.0
      name: qc
  total_runtime_seconds: 3600.0
```
